[강민성] Mission 3: 회원가입 기능 구현
wecode-bootcamp-korea/28-westagram-backend-2-team pull request #11
Opened 2021-12-20 07:05 UTC by nonasking

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 회원가입 뷰 작성(views.py)
- 회원가입 라우팅(urls.py)
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 이메일 validation을 함수화할 수는 없나요? (예시) 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [ ] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [ ] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [ ] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [ ] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-12-20 12:21 UTC, Kang-kyunghun requested changes

2021-12-20 12:21 UTC, Kang-kyunghun commented on students/minsung/users/views.py
> +            return JsonResponse({"message": "KEY_ERROR"}, status=400)
```suggestion
            
            return JsonResponse({"message": "SUCCESS"}, status=201)
        except KeyError:
            return JsonResponse({"message": "KEY_ERROR"}, status=400)
```
해당 공백은 없어도 될 것 같습니다.

2021-12-20 12:21 UTC, Kang-kyunghun commented on students/minsung/users/views.py
> +password_validator = re.compile('^(?=.*[a-zA-Z])(?=.*[!@#$%^*+=-])(?=.*[0-9]).{8,}$')
정규표현식을 사용할 경우, 자주 사용되는 경우가 아니라면 `compile()`해서 사용하지 않고, `match()`를 사용하는 것을 공식 문서에서 추천하고 있습니다.

2021-12-20 12:21 UTC, Kang-kyunghun commented on students/minsung/users/views.py
> +                return JsonResponse({"message": "DUPLICATED PHONE_NUMBER"}, status=409)
409 에러코드를 사용한 이유를 코멘트로 남겨주세요.

2021-12-20 12:23 UTC, Kang-kyunghun requested changes

2021-12-20 12:23 UTC, Kang-kyunghun commented on students/minsung/users/views.py
> +                return JsonResponse({"message": "INVALID EMAIL"}, status=400)
1. ==None이라는 표현은 잘 사용하지 않습니다. None 자체가 False로 인식되기 때문입니다.
2. 아래 예시가 complie을 사용하지 않았을 때의 예시입니다.
3. if문 다음 공백은 다 제거해 주세요.(if문끼리는 공백 유지)

```suggestion
regex_email = re.match('^[a-zA-Z0-9+-_.]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+$', email)

if not regex_email:              
    return JsonResponse({'message':'Invalid email format'}, status=400)

```

2021-12-21 01:36 UTC, nonasking commented on students/minsung/users/views.py
> +                return JsonResponse({"message": "DUPLICATED PHONE_NUMBER"}, status=409)
이미 DB에 있는 정보와 POST하는 정보가 같은 경우의 에러이기 때문에, 클라이언트의 요청과 서버가 충돌하는 경우의 에러인 409가 적절하지 않을까 생각했습니다. 혹시 더 적절한 다른 코드가 있을까요?

2021-12-21 01:50 UTC, Kang-kyunghun commented on students/minsung/users/views.py
> +        regex_password = re.match('^(?=.*[a-zA-Z])(?=.*[!@#$%^*+=-])(?=.*[0-9]).{8,}$', data['password'])
공백 제거해 주세요.
```suggestion
        regex_email    = re.match('^[\w]+@[\w]+\.[\w]+$', data['email'])
        regex_password = re.match('^(?=.*[a-zA-Z])(?=.*[!@#$%^*+=-])(?=.*[0-9]).{8,}$', data['password'])
```

2021-12-21 01:52 UTC, Kang-kyunghun commented on students/minsung/users/views.py
> +                return JsonResponse({"message": "DUPLICATED PHONE_NUMBER"}, status=409)
409에러는 주로 put method에서 file을 수정 할 때 충돌날 경우 많이 사용하는 에러 코드입니다. 다음과 같은 상황에서는 일반적으로 400을 많이 사용합니다. 그런데 status 코드에는 완벽한 정답은 없습니다. stackoverflow에서도 각자의 의견에 따라 400이 맞다 409가 맞다라고 의견을 주고 받는 것을 볼 수 있습니다.

2021-12-21 02:22 UTC, nonasking commented on students/minsung/users/views.py
> +                return JsonResponse({"message": "DUPLICATED PHONE_NUMBER"}, status=409)
네 알려주셔서 감사합니다 :)

2021-12-21 02:22 UTC, nonasking commented on students/minsung/users/views.py
> +        regex_password = re.match('^(?=.*[a-zA-Z])(?=.*[!@#$%^*+=-])(?=.*[0-9]).{8,}$', data['password'])
공백 수정했습니다! 확인 부탁드립니다

2021-12-21 02:28 UTC, Kang-kyunghun commented
LGTM~!!

2021-12-21 02:28 UTC, merged