[지원석] Mission 3: 회원가입 기능 구현
wecode-bootcamp-korea/28-westagram-backend-2-team pull request #12
Opened 2021-12-20 08:16 UTC by wsji91

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 회원가입 기능 구현 & 정규식 표현 관련 생성
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- 정규식을 위한 validators.py 를 따로 만들어 봄
- 일부러 user를 추가할 때, email='@gmail.com' 이런식으로, 빈칸에다가 골뱅이~ 이런식으로 httpie로 POST를 해보려고 하면, INVALID_EMAIL이 반환되는 것이 아니라 아예 error가 나는데, 해결이 안됨....

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- views.py 의 32,33 줄에 ValidationError... 관련해서 코드를 짰는데, 생각해보니 이 코드가 과연 필요한 것인가..? 이미 14,15 줄에서 결과가 나오는게 아닌가..? 스스로 이해가 명확하지 않은 상황에서 진행을 한 상태입니다ㅜㅜ

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-12-20 12:11 UTC, Kang-kyunghun requested changes

2021-12-20 12:11 UTC, Kang-kyunghun commented on students/wonsuk/westagram/users/validators.py
> +        raise ValidationError('INVALID_EMAIL')
```suggestion
    EMAIL_REGEX = "^[a-zA-Z0-9+-\_.]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+$"
   
     if not re.match(EMAIL_REGEX, email):
        raise ValidationError('INVALID_EMAIL')
```

2021-12-20 12:11 UTC, Kang-kyunghun commented on students/wonsuk/westagram/users/validators.py
> +    if not re.match(PASSWORD_REGEX, password):
```suggestion
    PASSWORD_REGEX = "^(?=.*[A-Za-z])(?=.*\d)(?=.*[$@$!%*#?&])[A-Za-z\d$@$!%*#?&]{8,}$"
   
     if not re.match(PASSWORD_REGEX, password):
```

2021-12-20 12:11 UTC, Kang-kyunghun commented on students/wonsuk/westagram/users/views.py
> +from users.validators       import email_regex_match, password_regex_match
```suggestion
from django.views           import View

from users.models           import User
from users.validators       import email_regex_match, password_regex_match
```

2021-12-20 12:11 UTC, Kang-kyunghun commented on students/wonsuk/westagram/users/views.py
> +
```suggestion
```
불필요한 공백 제거해 주세요.

2021-12-20 12:11 UTC, Kang-kyunghun commented on students/wonsuk/westagram/users/views.py
> +                return JsonResponse({'message' : 'EMAIL_ALREADY_EXISTS'}, status=401)
401코드가 언제 사용하는 코드인지 코멘트로 남겨주시고, 적절한 에러코드로 수정해 주세요.

2021-12-20 12:11 UTC, Kang-kyunghun commented on students/wonsuk/westagram/users/views.py
> +            return JsonResponse({'message' : e.message}, status=401)
여기도 적절한 에러코드로 수정해 주세요.

2021-12-20 12:11 UTC, Kang-kyunghun commented on students/wonsuk/westagram/users/views.py
> +                                )
```suggestion
            User.objects.create(
                username     = data['username'],
                email        = data['email'],
                password     = data['password'],
                phone_number = data['phone_number'],
                age          = data['age']
            )
```
줄바꿈 후 에는 4칸만 더 들여써주세요.

2021-12-21 03:33 UTC, wsji91 commented on students/wonsuk/westagram/users/views.py
> +                return JsonResponse({'message' : 'EMAIL_ALREADY_EXISTS'}, status=401)
401 에러코드는 해당 리소스에 유효한 인증 자격 증명이 없기 때문에 요청이 적용되지 않았음을 나타내는 것이라 합니다ㅜㅜ 각각의 에러코드의 의미를 모르고 그냥 막 가져다가 붙였었습니다^^; 적절한 코드는 400으로 수정해야할 것 같습니다

2021-12-21 04:09 UTC, Kang-kyunghun commented
raise는 해당 except 발동 시키는 역할입니다. raise가 작동하면 마지막 줄에 ValidationError를 정의한 부분이 동작 한다고 보시면 됩니다.

2021-12-21 04:09 UTC, merged