[강민성] Mission 4: 로그인 기능 구현
wecode-bootcamp-korea/28-westagram-backend-2-team pull request #14
Opened 2021-12-21 02:41 UTC by nonasking

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 로그인 뷰 구현
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- 이름 혹은 패스워드가 입력되지 않았을 시 KEYERROR 반환
- 이름 혹은 패스워드가 DB에 존재하지 않을 시 401 에러 반환
- 이름과 패스워드가 일치하는 사용자 정보가 DB에 있으면 로그인 성공

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 이메일 validation을 함수화할 수는 없나요? (예시) 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [ ] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [ ] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [ ] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [ ] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-12-21 07:12 UTC, kyeongraekim requested changes
아래 내용 확인 후 수정 반영해주세요!~

2021-12-21 07:12 UTC, kyeongraekim commented on students/minsung/users/urls.py
> +    path('/log_in', LoginView.as_view()),
RestfulAPI에 입각한 URI 설정에 의거하여 언더바 사용은 지양해주셔야 합니다. signin, sign-in, login, log-in 등으로 변경해주세요!~

2021-12-21 07:12 UTC, kyeongraekim commented on students/minsung/users/views.py
> +                return JsonResponse({"message": "SUCCESS"}, status=200)
가독성이 좋지 않고 불필요한 조건절이 중첩되어 있는 코드처럼 보이네요!~  아래 코드를 참조하여
filter() 메소드의 용법을 좀 더 리서치하여서 학습해주시고, 왜 불필요한 elif문을 제거해야하는지 고민해보세요!~

```python
def post(self, request):
    data = json.loads(request.body)

    if not User.objects.filter(email = data["email"], password = data["password"]).exists():
		    return JsonResponse({'message' : 'INVALID_USER'}, status=401)

		return JsonResponse({'message' : 'LOGIN SUCCESS'}, status=200)
```

2021-12-21 07:28 UTC, nonasking commented on students/minsung/users/urls.py
> +    path('/log_in', LoginView.as_view()),
수정했습니다! 노션에서 관련 자료 찾아서 좀 더 공부하도록 하겠습니다.

2021-12-21 07:34 UTC, nonasking commented on students/minsung/users/views.py
> +                return JsonResponse({"message": "SUCCESS"}, status=200)
1. INVALID USER 에러가 발생하는 조건을, 일치하는 이메일이 없거나/ 일치하는 패스워드가 없는 두 가지 경우로 나눠야 한다고 생각했습니다. 그런데 올려주신 코드와 조건을 좀 더 생각해보니, INVALID USER 에러가 발생하는 조건을 이메일, 패스워드와 일치하는 정보가 없는 경우 한 가지로 보고 조건문을 만드는 것이 더 좋은 방향이라는 것을 알았습니다.
2. 불필요한 elif문을 제거하니 코드가 좀 더 깔끔해지고, 이해하기도 쉬워진 것 같습니다.

검토와 코멘트 감사합니다. :)

2021-12-22 01:42 UTC, Kang-kyunghun requested changes

2021-12-22 01:42 UTC, Kang-kyunghun commented on students/minsung/users/views.py
> +                return JsonResponse({"message": "SUCCESS"}, status=200)
```suggestion
            if not User.objects.filter(email = data["email"], password = data["password"]).exists():
                return JsonResponse({"message": "INVALID_USER"}, status=401)
            
            return JsonResponse({"message": "SUCCESS"}, status=200)
```

2021-12-22 04:04 UTC, nonasking commented on students/minsung/users/views.py
> +                return JsonResponse({"message": "SUCCESS"}, status=200)
수정할 때 실수가 있었네요! 다시 수정해서 올렸으니 검토 부탁드립니다 :)

2021-12-22 04:20 UTC, Kang-kyunghun commented
LGTM~!!

2021-12-22 04:20 UTC, merged