[장우경] Mission 4: 로그인 기능 구현
wecode-bootcamp-korea/28-westagram-backend-2-team pull request #15
Opened 2021-12-21 03:50 UTC by Bruno-Jang

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 로그인 엔드포인트 구현
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-12-21 07:16 UTC, kyeongraekim requested changes
아래 내용 확인하여 수정해주세요!~

2021-12-21 07:16 UTC, kyeongraekim commented on students/woogyeong/westagram/users/views.py
> +                return JsonResponse({'message': '이메일과 비번이 맞지 않습니다.'}, status=400)
가독성이 좋지 않고 불필요한 조건절이 중첩되어 있는 코드처럼 보이네요!~ 아래 코드를 참조하여
filter() 메소드의 용법을 좀 더 리서치하여서 학습해주시고, 왜 불필요한 elif-else로 이어지는 중첩된 조건절 구조를 지양해야하는지 고민해보세요!~

```python
def post(self, request):
    data = json.loads(request.body)

    if not User.objects.filter(email = data["email"], password = data["password"]).exists():
		    return JsonResponse({'message' : 'INVALID_USER'}, status=401)

		return JsonResponse({'message' : 'LOGIN SUCCESS'}, status=200)
```

2021-12-21 07:16 UTC, kyeongraekim commented on students/woogyeong/westagram/users/views.py
> +            user_id = user.user_id
user_id는 정수로 이루어진 user_id pk 값을 말하는 것일까요? 그게 아니라면 혼동을 피하기 위해 변수명 변경이 불가피해보입니다!~

2021-12-22 01:41 UTC, Kang-kyunghun requested changes

2021-12-22 01:41 UTC, Kang-kyunghun commented on students/woogyeong/westagram/users/views.py
> +                return JsonResponse({'message': f"SUCCESS! user_id : '{userID}' successfully logged in"}, status=200)
email이 이미 유니크 한 값일 것 같은데, 그러면 해당 로직은 없어도 되지 않을까 생각 됩니다.

2021-12-22 01:41 UTC, Kang-kyunghun commented on students/woogyeong/westagram/users/views.py
> +            user    = User.objects.get(email=email)
user가 존재하는지 여부 판단 이전에 get을 통해 가져오게 되면 DB에 user가 없을 때 에러가 발생하게 됩니다.
따라서 전체적으로 코드가 다음과 같이 흘러가면 될 것 같습니다.

JWT를 적용하면 SUCCESS 대신에 토큰을 전달할 예정이지만, 지금 미션에서는 success만으로 충분합니다.
```suggestion
           if not User.objects.filter(email=email, password=password).exists():
                return JsonResponse({'message': 'INVALID_USER'}, status=401)
           
           return JsonResponse({'message': 'SUCCESS'}, status=200)
```

2021-12-22 01:41 UTC, Kang-kyunghun commented on students/woogyeong/westagram/users/views.py
> +                return JsonResponse({'message': f"SUCCESS! user_id : '{userID}' successfully logged in"}, status=200)
만약 어떤 user가 로그인 했는지를 보내고 싶으면 dictionary 구조로 만들어서 보내주시면 됩니다.
```suggestion
                result = {
                    'id'      : user.id,
                    'user_id' : user.user_id,
                    'name'    : user.name
                }
                return JsonResponse({'result':result }, status=200)
```

2021-12-22 01:41 UTC, Kang-kyunghun commented on students/woogyeong/westagram/users/views.py
> +            return JsonResponse({'message': '이메일과 비번이 맞지 않습니다.'}, status=400)
에러 메시지는 영어를 사용해 주세요.

2021-12-22 04:37 UTC, Bruno-Jang commented on students/woogyeong/westagram/users/views.py
> +                return JsonResponse({'message': f"SUCCESS! user_id : '{userID}' successfully logged in"}, status=200)
경훈님 감사합니다! 이런 식으로 리턴을 나오게 하고 싶었어요

2021-12-22 07:03 UTC, kyeongraekim approved these changes
LGTM!~

2021-12-22 07:03 UTC, merged