[지원석] Mission 4: 로그인 기능 구현
wecode-bootcamp-korea/28-westagram-backend-2-team pull request #16
Opened 2021-12-21 04:57 UTC by wsji91

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 로그인뷰 생성 후 오류 상황들 체크
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- 우선 의식의 흐름대로 로그인뷰를 짜봄

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 44,45번째 줄의 if email=="" or password=="": ...이 부분이 필요한 것일까요?

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-12-21 07:22 UTC, kyeongraekim requested changes
아래 내용 참고하여 수정해주세요!~

2021-12-21 07:22 UTC, kyeongraekim commented on students/wonsuk/westagram/users/views.py
> +            if password != User.objects.get(email=email).password:
가독성을 위해 != 좌우에 놓인 순서를 바꾸어 주시는 것은 어떨까요?

2021-12-21 07:22 UTC, kyeongraekim commented on students/wonsuk/westagram/users/views.py
> +            if email == "" or password == "":
빈값으로 오는 것과 키에 해당하는 벨류가 없는 것에는 차이가 있습니다! 아래 except 문으로 41&42번 라인에서 원하는 키-벨류를 찾지 못할 시 키에러를 발동시키게 설정을 해주셔서 해당 조건절은 필요 없어 보입니다.

2021-12-21 07:22 UTC, kyeongraekim commented on students/wonsuk/westagram/users/views.py
> +            if password != User.objects.get(email=email).password:
아까 구두로 전달드린 사항에 추가사항으로 filter() 메소드에 조건을 다양하게 넣을 수 있습니다. filter(a, b, c) 등의 형태로 말이죠. 한 번 고민하여 코드를 좀 더 줄여보세요!~

2021-12-21 08:00 UTC, wsji91 commented on students/wonsuk/westagram/users/views.py
> +            if password != User.objects.get(email=email).password:
> 아까 구두로 전달드린 사항에 추가사항으로 filter() 메소드에 조건을 다양하게 넣을 수 있습니다. filter(a, b, c) 등의 형태로 말이죠. 한 번 고민하여 코드를 좀 더 줄여보세요!~

넵! get 대신 filter메서드를 써서 수정해보았습니다.

2021-12-22 01:25 UTC, Kang-kyunghun requested changes

2021-12-22 01:25 UTC, Kang-kyunghun commented on students/wonsuk/westagram/users/views.py
> +
아래 if 로직에서 email과 password를 동시에 확인하므로 없어도 될 것 같습니다.

2021-12-22 01:47 UTC, wsji91 commented on students/wonsuk/westagram/users/views.py
> +
> 아래 if 로직에서 email과 password를 동시에 확인하므로 없어도 될 것 같습니다.

넵! 삭제해도 잘 돌아가는 것 같습니다. 감사합니당

2021-12-22 02:02 UTC, Kang-kyunghun commented
LGTM~!!

2021-12-22 04:20 UTC, merged