[이찬영] Mission 4: 로그인 기능 구현
wecode-bootcamp-korea/28-westagram-backend-2-team pull request #17
Opened 2021-12-21 06:17 UTC by coldzero94

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 로그인 기능 구현
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- 이메일로 로그인 가능
- 비밀번호 미 일치시 오류 메세지 401 발송

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [ ] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [ ] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [ ] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [ ] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-12-21 12:14 UTC, Kang-kyunghun requested changes

2021-12-21 12:14 UTC, Kang-kyunghun commented on students/chan/westagram/users/views.py
> +                return JsonResponse({'Message' : 'INVALID_USER'}, status=401)
INPUT으로 받은 email과 password를 동시에 만족하는 User를 조회 하도록 코드를 작성하면 가독성이 더 좋아질 것 같습니다. (당연히 코드가 처리해야되는 로직도 간단해 지겠죠?)

```python
if not User.objects.filter(email = data["email"], password = data["password"]).exists:
    return JsonResponse({'message' : 'INVALID_USER'}, status=401)
```

2021-12-22 04:30 UTC, coldzero94 commented on students/chan/westagram/users/views.py
> +                return JsonResponse({'Message' : 'INVALID_USER'}, status=401)
요청하신 수정사항 완료하였습니다.~!

2021-12-22 07:01 UTC, merged

2021-12-22 07:01 UTC, kyeongraekim commented
LGTM!~