[강민성] Mission 5: 회원가입 비밀번호 암호화 적용
wecode-bootcamp-korea/28-westagram-backend-2-team pull request #18
Opened 2021-12-22 04:56 UTC by nonasking

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
- 회원가입시 입력하는 비밀번호가 암호화되게 코드 수정
		 
## 수정 사항들 자세한 내용
- 회원가입시 입력하는 비밀번호가 bcrypt의 hashpw함수로 암호화되고, 그 값에 decode를 적용하여 암호화된 문자열 형태로 DB에 저장되도록 했습니다.

## 기타 질문 및 특이 사항
- hashpw함수를 사용할 때 salt값은 어떻게 주는 것이 좋은가요?

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [ ] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [ ] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [ ] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [ ] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-12-22 07:01 UTC, kyeongraekim requested changes
마이너한 수정 사항 반영 해주세요!~

2021-12-22 07:01 UTC, kyeongraekim commented on students/minsung/users/views.py
>                  date_of_birth = data['date_of_birth']
date_of_birth 는 모델상 null=True로 되어 널값을 받을 수 있네요. 선택기입 정보라고 보여지는데 키에러를 내야만하는 view 파일 코드상 모순이 보인다고 생각됩니다. 파이썬 딕셔너리 메소드 주 하나인 data.get('') 메소드를 사용하여서 수정해 보는 것을 고민해보세요!~

2021-12-22 08:13 UTC, nonasking commented on students/minsung/users/views.py
>                  date_of_birth = data['date_of_birth']
알려주신 메소드를 사용해서 예외처리를 해봤습니다! 검토 부탁드립니다 :)

2021-12-23 01:21 UTC, nonasking commented on students/minsung/users/views.py
>                  date_of_birth = data['date_of_birth']
Mission 6에서 import할 내용이 적혀있는 부분이 있어서 삭제했습니다!

2021-12-23 02:26 UTC, Kang-kyunghun requested changes

2021-12-23 02:26 UTC, Kang-kyunghun commented on students/minsung/users/views.py
> +
경래님이 review 주신 내용을 잘 못 이해 한 것 같습니다. 
dictionary의 value를 가져올 수 있는 get method의 사용법과 역할을 한 번 더 확인해 보시고, 리뷰드린 내용을 생각해 보면 좋을 것 같습니다.

2021-12-23 05:29 UTC, nonasking commented on students/minsung/users/views.py
>                  date_of_birth = data['date_of_birth']
말씀해주신대로 반영했습니다!

2021-12-23 07:49 UTC, kyeongraekim approved these changes
LGTM!~

2021-12-23 07:49 UTC, merged