[이찬영] Mission 5: 회원가입 비밀번호 암호화 적용
wecode-bootcamp-korea/28-westagram-backend-2-team pull request #19
Opened 2021-12-22 08:38 UTC by coldzero94

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 회원가입시 해쉬 적용
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- 회원가입 할때 hash 및 salt 적용 완료
- password 다시 저장 해줄떄 decode 해줘서 문자열로 저장
## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
-

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [ ] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [ ] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [ ] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [ ] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-12-22 12:52 UTC, coldzero94 commented
DB 적재된 해쉬암호화된 bcrypt.checkpw 추가 까지 하였습니다.

2021-12-23 02:23 UTC, Kang-kyunghun requested changes

2021-12-23 02:23 UTC, Kang-kyunghun commented on students/chan/westagram/users/views.py
> +            if not bcrypt.checkpw(password.encode('utf-8'),User.objects.filter(email=email).get().password.encode('utf-8')):
로직은 맞으나 가독성을 조금 더 좋게 하기 위해 다음과 같이 수정하면 좋을 것 같습니다.
```suggestion
            user = User.objects.get(email=email)
            
            if not bcrypt.checkpw(password.encode('utf-8'), user.password.encode('utf-8')):
```

2021-12-23 02:23 UTC, Kang-kyunghun commented on students/chan/westagram/users/views.py
> +                return JsonResponse({'Message' : 'INVALID_PASSWORD'}, status=401)
email이 틀렸을 경우와 비민번호가 틀렸을 경우 같은 메시지를 보내는 것이 보안상 더 좋습니다.
```suggestion
                return JsonResponse({'Message' : 'INVALID_USER'}, status=401)
```

2021-12-23 03:04 UTC, coldzero94 commented on students/chan/westagram/users/views.py
> +                return JsonResponse({'Message' : 'INVALID_PASSWORD'}, status=401)
1. 요청하신 가독성 향상을 위한 코드 간략화 진행하였습니다.
2. 보안을 위하여 email 비밀번호 틀렸을 경우 같은 메세지 보내기위해
 Message : INVALID_USER 로 통일 하였습니다.

2021-12-23 07:49 UTC, merged