[강민성] Mission 2: 모델링
wecode-bootcamp-korea/28-westagram-backend-2-team pull request #4
Opened 2021-12-16 10:40 UTC by nonasking

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## models.py 작성
		 
## 수정 사항들 자세한 내용
name, email, password, phone_number 추가
그 외 개인정보로 age 추가

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 이번 과제에서 앱을 만들면서 url 설정 없이 모델만 만들었는데, url 설정은 다음 과제에서 하는 것이 맞나요? 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [ ] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [ ] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [ ] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [ ] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-12-16 15:27 UTC, kyeongraekim requested changes
아래 수정 사항 확인 후 반영해주세요!!~

2021-12-16 15:27 UTC, kyeongraekim commented on students/minsung/users/models.py
> +    age          = models.IntegerField()
- email에 대한 max_length가 너무 길어 보이네요!~ 100자 정도로 두어서 데이터 활용 면에서 딱 원하는 정도만 사용하는 것이 좋아 보입니다. 개발자, 기획자의 시선에서 불필요한 자원의 소비를 줄이는 습관을 미리 들여보세요!~
- 통상적인 웹서비스 기획상 사용자 계정의 비밀번호에 정수만 들어갈까요? 다른 데이터 값이 어떤게 들어갈지 생각해보시고, 올바른 데이터 형태와 올바른 데이터 양을 한 번 고민해주세요!
- 전화번호도 마찬가지입니다. 국제 전화번호 특성상 다양한 특수기호가 들어갈 수가 있다는 판단하에 정수값만 넣지 않고 다른 기획을 한 번 고민해보세요!~
- 나이는 필수 정보가 아니어도 될 것 같아 보이네요. Null을 허용해보는 것은 어떨까요? 실제 인스타그램에서 필요로하는 핋수 정보가 아닌 선택기입정보가 어떤 것이 있을지 찾아보는 것도 추천드립니다!~

2021-12-17 02:17 UTC, nonasking commented on students/minsung/users/models.py
> +    age          = models.IntegerField()
네 반영해서 다시 수정했습니다! 검토 부탁드립니다 :)

2021-12-17 02:43 UTC, kyeongraekim requested changes
민성님 아래 내용 확인하여 수정 반영해주세요!~

2021-12-17 02:43 UTC, kyeongraekim commented on students/minsung/users/models.py
> +# Create your models here.
불필요한 주석은 삭제해주세요!~

2021-12-17 02:43 UTC, kyeongraekim commented on students/minsung/users/models.py
> +    password      = models.CharField(max_length=30)
비밀번호는 추후 암호화 해싱 작업에 대한 가능성을 염두하여 최소 256자 정도로는 최대 길이를 조정해주세요!

2021-12-17 02:51 UTC, nonasking commented on students/minsung/users/models.py
> +    password      = models.CharField(max_length=30)
검토 감사합니다! 두 가지 모두 수정했습니다. 확인 부탁드립니다

2021-12-17 07:09 UTC, Kang-kyunghun requested changes

2021-12-17 07:09 UTC, Kang-kyunghun commented on students/minsung/users/models.py
> +
데이터의 이력 관리를 위해서 created_at, updated_at column을 추가해주세요.

```python
created_at = models.DateTimeField(auto_now_add=True)
updated_at = models.DateTimeField(auto_now=True)
```

2021-12-17 07:21 UTC, nonasking commented on students/minsung/users/models.py
> +
검토 감사합니다! 수정했습니다. 확인 부탁드립니다

2021-12-18 01:33 UTC, Kang-kyunghun commented
LGTM~!!

2021-12-18 01:33 UTC, merged