[지원석] Mission 2: 모델링
wecode-bootcamp-korea/28-westagram-backend-2-team pull request #6
Opened 2021-12-17 02:43 UTC by wsji91

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- User class 작성 (회원들 정보 데이터 테이블)
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- 사용자 정보에는 '이름, 이메일, 비밀번호, 전화번호, 그 외 정보' 포함됨
- 'users'로 db_table 명 설정

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 모든 정보를 CharField로 지정하여 문자 길이에 대한 조건만 주었는데, 어떠한 고려사항들이 필요할까요? 예를 들면, 비밀번호는 필수 이런 설정이 있을까요? null값 안된다 이런거..? 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-12-17 02:45 UTC, kyeongraekim requested changes
아래 내용 확인하여 수정해주세요!~

2021-12-17 02:45 UTC, kyeongraekim commented on students/wonsuk/westagram/users/models.py
> +    password = models.CharField(max_length=100)
비밀번호는 추후 암호화 될 가능성을 염두하여 최대 길이를 최소 256자로는 맞추어 주세요.

2021-12-17 02:45 UTC, kyeongraekim commented on students/wonsuk/westagram/users/models.py
> +    name = models.CharField(max_length=50)
일반 이름이 아닌 계정이름이 될 가능성을 고려하여 username으로 변수명을 바꾸어 보는 것은 어떨까요?

2021-12-17 02:45 UTC, kyeongraekim commented on students/wonsuk/westagram/users/models.py
> +    other_information = models.CharField(max_length=300)
전반적으로 위코드 컨벤션에 맞게 제일 긴 변수명을 기준으로 한 칸만 스페이싱을 해주셔서 정렬을 해주세요!~

2021-12-17 02:54 UTC, wsji91 commented on students/wonsuk/westagram/users/models.py
> +    password = models.CharField(max_length=100)
대박 빠른 코멘트 경래님! 감사합니다!! 비번은 최대길이 최소 256! 안까먹을 것 같습니다

2021-12-17 07:08 UTC, Kang-kyunghun requested changes

2021-12-17 07:08 UTC, Kang-kyunghun commented on students/wonsuk/westagram/users/models.py
> +
1. 그 외 정보는 혹시 추가할 만한 컬럼이 있으면 추가하라는 의미 였습니다. 따라서 other_information은 제거해도 좋을 것 같습니다.
2. 데이터의 이력 관리를 위해서 created_at, updated_at column을 추가해주세요.

```python
created_at = models.DateTimeField(auto_now_add=True)
updated_at = models.DateTimeField(auto_now=True)
```

2021-12-17 08:08 UTC, wsji91 commented on students/wonsuk/westagram/users/models.py
> +
네 감사합니다 경훈님:) 진행하겠습니다!

2021-12-18 01:49 UTC, Kang-kyunghun requested changes

2021-12-18 01:49 UTC, Kang-kyunghun commented on students/wonsuk/westagram/users/models.py
> +
공백 제거해 주세요.

2021-12-18 01:49 UTC, Kang-kyunghun commented on students/wonsuk/westagram/users/views.py
> +
3번 과제는 다른 브렌치에서 작업해 주시고, 해당 브렌치에는 코드가 안 올라오게 제거 후 다시 push해 주세요.

2021-12-19 15:20 UTC, wsji91 commented on students/wonsuk/westagram/users/models.py
> +
> 공백 제거해 주세요.

넵, 제거했습니다.

2021-12-19 23:48 UTC, Kang-kyunghun commented
LGTM~~!!

2021-12-19 23:48 UTC, merged