ADD - model created
wecode-bootcamp-korea/28-westagram-backend-2-team pull request #7
Opened 2021-12-17 04:54 UTC by Bruno-Jang

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 로그인 엔드포인트 구현(예시)
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- 이메일 또는 핸드폰 번호로 로그인할 수 있음
- 실패시 에러 반환
- 성공시 200 OK 반환

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 이메일 validation을 함수화할 수는 없나요? (예시) 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-12-17 07:04 UTC, Kang-kyunghun requested changes

2021-12-17 07:04 UTC, Kang-kyunghun commented on students/woogyeong/westagram/users/models.py
> +    register_date = models.DateTimeField(auto_now_add=True)
1. brank =True을 사용한 이유룰 코멘트로 남겨주세요.
2. 데이터의 이력 관리를 위해서 created_at, updated_at column을 추가해주세요.

```python
created_at = models.DateTimeField(auto_now_add=True)
updated_at = models.DateTimeField(auto_now=True)
```

2021-12-17 07:31 UTC, Bruno-Jang commented on students/woogyeong/westagram/users/models.py
> +    register_date = models.DateTimeField(auto_now_add=True)
경훈님 리뷰 감사합니다!
저는 register_date = models.DateTimeField(auto_now_add=True) 이렇게 만들어 뒀었는데
register_date를 created_at으로 바꾸기만 해도 될까요?
두 개의 역할이 같을거 같아서 여쭤봅니다~

2021-12-17 09:07 UTC, Bruno-Jang commented on students/woogyeong/westagram/users/models.py
> +    register_date = models.DateTimeField(auto_now_add=True)
1. 사실 null과 blank의 차이를 정확히 알지 못한 상태에서 코드를 작성했습니다.
찾아보니 null은 DB와 직접적인 연관이 있고 blank는 django forms에서 유효성 검사와 관련이 있다고 찾았습니다.
제가 의도했던 바는 생년월일을 빈칸으로 둬도 회원가입이 가능하도록 하고 싶었습니다.
그래서 현재로서는 데이터의 유효성 검사가 어떻게 될지 잘 모르기에 우선 빼고 null=True만 남겨뒀습니다.
혹시 blank와 관련해서 추가해주실 부분이 있으시다면 말씀 부탁드리겠습니다.

2. created_at과 updated_at column 추가했습니다!

2021-12-18 01:47 UTC, Kang-kyunghun commented on students/woogyeong/westagram/users/models.py
> +    register_date = models.DateTimeField(auto_now_add=True)
우경님 잘 찾아보셨습니다.!!
blank=True는 django form에서 blank의 허용 여부를 경정하는 속성입니다. 그래서 blank보다 Null 속성을 사용하는 것이 적절해 보입니다.

2021-12-18 01:47 UTC, merged