ADD : users app
wecode-bootcamp-korea/28-westagram-backend-2-team pull request #8
Opened 2021-12-17 06:02 UTC by coldzero94

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- user 앱 추가 및 개인정보항목 생성완료
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 다음과제 3번도 새로운 브랜치에서 작업을 시작해야될까요?
- Field의 다양성을 주는것이 어려운것 같습니다 ㅜㅜ

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [ ] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [ ] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [ ] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [ ] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-12-17 07:03 UTC, Kang-kyunghun requested changes

2021-12-17 07:03 UTC, Kang-kyunghun commented on students/chan/westagram/users/models.py
> +    enterprize            = models.BooleanField(default=True)
```suggestion
    allowing_email_recive = models.BooleanField(default=True)
    enterprize            = models.BooleanField(default=True)
```
1. enterpize의 역할이 무엇인가요?? (궁금)
2. 보통 boolean을 사용할 경우 앞에 is_ 를 붙여서 이름을 만듭니다.
3. 데이터의 이력 관리를 위해서 created_at, updated_at column을 추가해주세요.

```python
created_at = models.DateTimeField(auto_now_add=True)
updated_at = models.DateTimeField(auto_now=True)
```

2021-12-17 08:46 UTC, coldzero94 commented on students/chan/westagram/users/models.py
> +    enterprize            = models.BooleanField(default=True)
1. eterprize의 역할은 기업회원인지 구분하기 위해서 넣었습니다.
2. boolean을 사용하기 위해서 앞에 is 추가 완료 하였습니다.
3. 데이터 이력관리를 위한 created_at, updated_at column 추가 완료하였습니다.

2021-12-17 08:58 UTC, coldzero94 commented on students/chan/westagram/users/models.py
> +    enterprize            = models.BooleanField(default=True)
models.py 에서 오타 추가 수정하였습니다.

2021-12-18 01:36 UTC, Kang-kyunghun commented
1. 3번 과제도 당연히 브렌치를 새로 만들어야 합니다.
2. field의 다양성보다는 적절한 필들를 사용했는지에 더 집중하시면 좋을 것 같아요.

2021-12-18 01:43 UTC, Kang-kyunghun requested changes

2021-12-18 01:43 UTC, Kang-kyunghun commented on students/chan/westagram/users/models.py
> +    personal_site            = models.URLField(max_length=200, blank=True)
```suggestion
    personal_site            = models.URLField(max_length=1000, blank=True)
```
url은 길이가 많이 길수도 있어서 1000정도 길이를 주는 것이 좋을 것 같아요.

2021-12-18 01:43 UTC, Kang-kyunghun commented on students/chan/westagram/users/models.py
> +    business_number          = models.CharField(max_length=50, blank=True)
blank = True가 django에서 어떻게 작용하고, 꼭 필요한지 blank =True 대신 무엇을 사용해야 할지 코멘트로 남겨주세요.

2021-12-18 01:43 UTC, Kang-kyunghun commented on students/chan/westagram/users/models.py
> +    email                    = models.EmailField(max_length=128, null=False, unique=True)
null=False는 기본값이므로 전부 제거해 주세요.
```suggestion
    email                    = models.EmailField(max_length=128, unique=True)
```

2021-12-18 05:54 UTC, coldzero94 commented on students/chan/westagram/users/models.py
> +    business_number          = models.CharField(max_length=50, blank=True)
blank = True 는 null = True값으로 대체하여서 사용 가능합니다.  
null = True는 필드의 값이 NULL(정보없음)로 저장되는 것을 허용합니다.
이건 데이터베이스와 관련이 있습니다. 

그러나 CharField, TextField와 같은 문자열 기반 필드에는 null = True로 하게되면 none과 빈 문자열을 갖게되는 중복이 일어납니다. 그렇기에 blank = True로 정의하여야 합니다.

2021-12-18 06:01 UTC, coldzero94 commented on students/chan/westagram/users/models.py
> +    email                    = models.EmailField(max_length=128, null=False, unique=True)
1. null = False 제거 완료하였습니다.
2. persnal_site 의 max_length 1000으로 수정 하였습니다.
3. null = True, Blank = True와의 차이점 공부 및 코멘트 작성하였습니다.

2021-12-18 06:58 UTC, Kang-kyunghun commented on students/chan/westagram/users/models.py
> +    business_number          = models.CharField(max_length=50, blank=True)
조금 정정을 하자면, blank 속성은 django의 form과 관련된 속성입니다.  CharField, TextField에서 brank = True을 걸고 빈 값이 들어올 경우 빈 문자열이 들어오게 됩니다. 
따라서 django에 의존된 속성인 blank 대신에 null 또는 default 속성을 사용해 주세요.

2021-12-18 22:57 UTC, coldzero94 commented
1. null = True 값으로 변경 완료 하였습니다.

2021-12-19 06:03 UTC, kyeongraekim requested changes
찬영님~ 간단한 수정사항 반영해서 올려주세요!

2021-12-19 06:03 UTC, kyeongraekim commented on students/chan/westagram/users/models.py
> +# Create your models here.
코드 진행에 불필요한 영문 주석은 제거해주세요~

2021-12-20 01:07 UTC, coldzero94 commented on students/chan/westagram/users/models.py
> +# Create your models here.
1. 간단한 수정사항 반영 완료하였습니다.
2. 코드진행에 불필요한 영문 주석 제거 완료하였습니다.

2021-12-20 01:19 UTC, kyeongraekim requested changes
찬영 이제 딱 한 가지만 수정해주시면 완성될 것 같아 보입니다!~

2021-12-20 01:19 UTC, kyeongraekim commented on students/chan/westagram/users/models.py
> +    phone_number             = models.CharField(max_length=11)
전화번호 max_length가 너무 짧게 설정되어있네요! 국제전화번호 및 특수기호가 들어갈 수 있을 만한 실제 인스타그램 기획에 맞게 최소 30자 이상으로 설정하는 것을 권장 드립니다!~

2021-12-20 02:28 UTC, coldzero94 commented on students/chan/westagram/users/models.py
> +    phone_number             = models.CharField(max_length=11)
1. 전화번호 max_length=50으로 변경 완료하였습니다!

2021-12-20 05:23 UTC, Kang-kyunghun commented
LGTM~!!

2021-12-20 05:23 UTC, merged