[장우경] Mission 3: 회원가입 기능 구현
wecode-bootcamp-korea/28-westagram-backend-2-team pull request #9
Opened 2021-12-18 15:49 UTC by Bruno-Jang

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 로그인 엔드포인트 구현(예시)
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- 이메일 또는 핸드폰 번호로 로그인할 수 있음
- 실패시 에러 반환
- 성공시 200 OK 반환

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 이메일 validation을 함수화할 수는 없나요? (예시) 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-12-18 16:05 UTC, Bruno-Jang commented
1. 정규식으로 유효성 검사할 때 re.match와 re.search를 많이 고민했는데 search 메소드로 작성했을 때 잘 되길래 match 메소드를 미처 테스트해보지 못 한 상태에서 제출했습니다..
match 메소드에 대해 찾아보니 문자열 처음부터 조건에 적합한지 본다고 해서 match가 더 적합하지 않을까 해서 지금 테스트해보려고 합니다. 테스트 후에 어려운 점이 있으면 여쭤보겠습니다!

2. 그리고 이메일 인증시 중복 여부와 이메일과 비밀번호 유효성 검사시 부적합할 경우 http 에러코드 409를 리턴하게 했습니다.
뭔가 서버와 충돌이 생기는 경우에 쓰는 에러 코드라고 봤는데 이메일 중복 여부의 경우에는 DB에 이미 데이터가 있는 문제이기에 중복을 막아놨을 경우에 서버와 충돌이 생길 수 있다는 점은 이해가 되지만
이메일과 비밀번호 유효성 검사에도 409 코드를 쓰는게 맞는 선택인지에 대해서는 확신이 들지 않아 여쭤봅니다.

2021-12-20 00:13 UTC, Kang-kyunghun requested changes

2021-12-20 00:13 UTC, Kang-kyunghun commented on students/woogyeong/westagram/users/views.py
> +                return False
굳이 다시 함수로 만들 필요 없이 아래 리뷰 내용처럼 바꾸면 좋을 것 같습니다.
만약에 따로 validator.py로 모듈을 만들었다면, 그 때는 함수화 시키는 것이 좋습니다.

2021-12-20 00:13 UTC, Kang-kyunghun commented on students/woogyeong/westagram/users/views.py
> +                    return JsonResponse({'message': 'INVALID_PASSWORD'}, status=409)
```suggestion
      if not re.match('^[a-zA-Z0-9+-_.]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+$', email)
                return JsonResponse({'message':'Email format is not valid'}, status=400)

        if not re.match('^(?=.*[A-Za-z])(?=.*\d)(?=.*[?!@#$%*&])[A-Za-z\d?!@#$%*&]{8,}$', password):
            return JsonResponse({'message':'Password format is not valid'}, status=400)
        
        if User.objects.filter(email=data['email']).exists():
                return JsonResponse({'message': 'USER_EXISTS'}, status=400)
```
1. match를 사용할 경우 compile 없이 바로 사용 가능합니다.
2. 정규 표현식 같은 경우 리뷰에는 직접 바로 넣어지만, 상수화 해도 좋을 것 같습니다.
3. validation error의 경우 보통 400을 많이 사용합니다. 409는 일반적으로 put method를 사용할 때 타겟 데이터랑 수정하려는 정보랑 충돌이 일어 났을 때 사용합니다.

2021-12-20 04:59 UTC, Bruno-Jang commented on students/woogyeong/westagram/users/views.py
> +                    return JsonResponse({'message': 'INVALID_PASSWORD'}, status=409)
경훈님 제가 함수를 만들어서 써본 경험이 거의 없어서 validators 라는 모듈을 만들어서 해당 함수들을 import 해봤습니다.
그리고 두번째 말씀하신 부분 상수화하는 것을 validators 모듈에 했는데 제가 이해한게 맞을까요~??

2021-12-20 05:11 UTC, Bruno-Jang commented on students/woogyeong/westagram/users/views.py
> +                    return JsonResponse({'message': 'INVALID_PASSWORD'}, status=409)
경훈님 제가 3번 미션하기 전에 branch를 따지 않아서 이 PR과 commit 삭제하고 새로 PR을 해도 될까요?

2021-12-20 05:19 UTC, Kang-kyunghun requested changes

2021-12-20 05:19 UTC, Kang-kyunghun commented on students/woogyeong/westagram/users/validators.py
> +
공백은 1줄로 해주세요.

2021-12-20 05:19 UTC, Kang-kyunghun commented on students/woogyeong/westagram/users/validators.py
> +
여기도 1줄로 해주세요.

2021-12-20 05:19 UTC, Kang-kyunghun commented on students/woogyeong/westagram/users/views.py
> +                return JsonResponse({'message': "CREATED"}, status=201)
```suggestion
            if not validate_email(data['email']):
                return JsonResponse({'message': 'Email format is not valid'}, status=400)
            
            if not validate_password(data['password']):
                return JsonResponse({'message': 'Password format is not valid'}, status=400)
            
            if User.objects.filter(email=data['email']).exists():
                return JsonResponse({'message': 'USER_EXISTS'}, status=400)
       
           User.objects.create(
                email         = data['email'],
                mobile        = data['mobile'],
                user_name     = data['user_name'],
                user_id       = data['user_id'],
                password      = data['password'],
            )
            return JsonResponse({'message': "CREATED"}, status=201)
```
1. if 조건을 만족하게 되면 return을 하므로 다시 elif로 안 묶어도 됩니다.
2. 위의 if 조건을 다 통과 했다는 것은 email, password가 조건을 다 만족한다는 의미이기 때문에 마지막 elif에 있던 조건을 없어도 될 것 같습니다.

2021-12-20 05:31 UTC, closed without merging